apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: service-name
    path: deployment-patch.json
  - target:
      version: v1
      kind: Secret
      name: service-secrets
    path: secret-patch.json
  - target:
      version: v1
      kind: Service
      name: service
    path: service-patch.json
