apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ccp-infrastructure-operator-prod
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: https://github.com/willmendezcuemby/gitops-ccp
    targetRevision: HEAD
    path: ./overlays/overlays/ccp-infrastructure-operator/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: my-prod-namespace
  syncPolicy:
    automated: {}
