apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iep-flood-service-staging
  namespace: argocd
spec:
  project: staging
  source:
    repoURL: https://github.com/willmendezcuemby/gitops-ccp
    targetRevision: HEAD
    path: ./overlays/overlays/iep-flood-service/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: my-staging-namesp
  syncPolicy:
    automated: {}
