apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ccp-application-service-dev
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: https://github.com/willmendezcuemby/gitops-ccp
    targetRevision: HEAD
    path: ./overlays/overlays/ccp-application-service/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: my-dev-namespace
  syncPolicy:
    automated: {}
